version: '3.8'
services:
  app:
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql://root:1234@db:3306/music

  db:
    image: mariadb:10.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: music

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8000:80"
    environment:
      PMA_ARBITRARY: '1'
      PMA_HOST: db
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: 1234
