name: vvault_tree-stock_backend
services:
  app:
    image: tree-stock_backend:latest
    restart: unless-stopped
    build:
      context: .
    ports:
      - 24000:4000
    volumes:
      # patch startup file
      - ./docker/startup-dev.sh:/startup.sh
      - .:/app
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
    extra_hosts:
      host: "host-gateway"
